# Generated by Django 3.2.7 on 2021-09-10 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextCollection',
            new_name='text_collection',
        ),
    ]
