# Generated by Django 3.2.7 on 2021-09-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_textcollection_text_collection'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='text_collection',
            table='text_collection',
        ),
    ]
